### ISSUE TITLE
Frame semantic transformer (FST) x LR'X'?

### ISSUE THREAD

**Issue by sdspieg** [chanind/linear-relational#3]
This once again looks really cool David! But so how would you describe the differences, relative pros and cons, AND maybe even complementarity between these two libraries/modules of yours? Imagine, for instance, that we'd be interested in extracting the different ways in which different countries' actions can trigger reactions from other countries. What would you think would be the best way to approach this? Could we first use FST to identify and parse out 'causal' semantic chunks (and frankly - this is not worked well for us so far) in a corpus as 'candidate' prompts; then have human experts filter these into TPs and FPs, and then use LR'X' to feed the TPs as prompts into this? Thoughts? Suggestions?

**Comment by chanind** [comment]
Hi Stephan - really cool to see you found this repo and you're thinking about the connection with semantic parsing! To be honest, I view these two projects as fundamentally different from each other in their goals and use-cases. FST is meant to be a frame parsing library that's directly usable to tag parts of sentences so it's really meant to be a tool for tagging sentences.

I know what you mean, though, I don't think the performance of FST is satisfactory for real tasks. I'm not sure if semantic parsing using things like FrameNet is just a doomed proposition to be honest. Given how powerful modern LLMs like GPT4 are, it seems like the best choice to do almost any practical language processing task is to just use a LLM. I don't think FST or really any frame parsing library can compete with creative prompting of GPT4.

This linear-relation library is an acknowledgement of that, and is meant as a way to try to understand what LLMs are doing internally as they compute outputs. I think that if you want to get real work done, you should just use a LLM directly and not bother with linear-relational or FST. My research direction has changed and I'm interested now in trying to understand how LLMs are achieving their incredible results and trying to dig into what's happening internally during LLM processing. Maybe if we can understand how LLMs are doing what they're doing then someday we can extract that part of the LLM and turn it into explicit understandable code, but  that seems really far off still.
